apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zip
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - zainproti.si
        - www.zainproti.si
      secretName: zip-tls
  rules:
    - host: zainproti.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zip
                port:
                  number: 8000
    - host: www.zainproti.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zip
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zip-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - files.zip.lb.djnd.si
      secretName: zip-nginx-tls
  rules:
    - host: files.zip.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zip-nginx
                port:
                  number: 80
