apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zip
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: zip
    newName: rg.fr-par.scw.cloud/djnd/zip
    newTag: '9d4e5fe720d336447730c161f2fabb8d06f6395b'
