# Generated by Django 5.2.3

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
            ],
            options={
                "verbose_name": "Event Category",
                "verbose_name_plural": "Event Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_us",
                    wagtail.fields.RichTextField(blank=True, verbose_name="About us"),
                ),
                (
                    "social_media_links",
                    wagtail.fields.StreamField(
                        [("social_media_link", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("bluesky", "Bluesky"),
                                        ("facebook", "Facebook"),
                                        ("instagram", "Instagram"),
                                        ("linkedin", "LinkedIn"),
                                        ("mastodon", "Mastodon"),
                                        ("threads", "Threads"),
                                        ("tiktok", "TikTok"),
                                        ("twitter", "Twitter"),
                                        ("vimeo", "Vimeo"),
                                        ("youtube", "YouTube"),
                                    ],
                                    "label": "Platform",
                                },
                            ),
                            1: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Link", "required": True},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("platform", 0), ("url", 1)]],
                                {"icon": "link", "label": "Social media link"},
                            ),
                        },
                        verbose_name="Social media links",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "newsletter_signup_title",
                    models.CharField(blank=True, max_length=255, verbose_name="Title"),
                ),
                (
                    "newsletter_signup_email_label",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Email label"
                    ),
                ),
                (
                    "newsletter_signup_consent_label",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Consent label"
                    ),
                ),
                (
                    "newsletter_signup_submit_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Submit text"
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Settings",
            },
        ),
        migrations.CreateModel(
            name="TeamPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Team Position",
                "verbose_name_plural": "Team Positions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HeaderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "navigation",
                    wagtail.fields.StreamField(
                        [("page_link", 2), ("external_link", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 255, "required": True},
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": True},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("page", 1)]],
                                {"icon": "link", "label": "Internal link"},
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Link", "required": True},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("url", 3)]],
                                {"icon": "link", "label": "External link"},
                            ),
                        },
                        verbose_name="Navigation",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Logo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header Settings",
            },
        ),
    ]
