# Generated by Django 5.2.3

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_aboutuspage_eventlistpage_eventpage_genericpage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("title_block", 4),
                    ("upcoming_events_block", 9),
                    ("latest_news_block", 11),
                    ("current_projects_block", 13),
                    ("promotion_block", 15),
                    ("newsletter_signup_block", 17),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Subtitle", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("description", 2),
                                ("image", 3),
                            ]
                        ],
                        {},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link text", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Next upcoming events.",
                            "label": "Displayed items",
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 5),
                                ("link_text", 6),
                                ("page", 7),
                                ("displayed_items", 8),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Latest news posts.",
                            "label": "Displayed items",
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 5),
                                ("link_text", 6),
                                ("page", 7),
                                ("displayed_items", 10),
                            ]
                        ],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Projects marked as current.",
                            "label": "Displayed items",
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 5),
                                ("link_text", 6),
                                ("page", 7),
                                ("displayed_items", 12),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 5),
                                ("image", 3),
                                ("description", 2),
                                ("link_text", 6),
                                ("url", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Newsletter signup texts are managed under Footer settings.",
                            "label": "More settings elsewhere",
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("more_settings_elsewhere", 16)]],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
    ]
