# Generated by Django 5.2.3 on 2025-06-24 19:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_eventlistpage_body_eventpage_body_eventpage_category_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectlistpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("current_projects_block", 4), ("past_projects_block", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link text", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Projects marked as current.",
                            "label": "Displayed items",
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("link_text", 1),
                                ("page", 2),
                                ("displayed_items", 3),
                            ]
                        ],
                        {},
                    ),
                    5: ("wagtail.blocks.StructBlock", [[("title", 0)]], {}),
                },
                verbose_name="Page body",
            ),
        ),
        migrations.AddField(
            model_name="projectlistpage",
            name="current_projects",
            field=wagtail.fields.StreamField(
                [("project", 0)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Project", "page_type": ["home.ProjectPage"]},
                    )
                },
                verbose_name="Current projects",
            ),
        ),
        migrations.AddField(
            model_name="projectpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text_block", 0),
                    ("gallery_block", 2),
                    ("material_list_block", 7),
                    ("current_projects_block", 11),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Text"}),
                    1: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {"admin_text": "Not implemented!", "label": "TODO"},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("todo", 1)]], {}),
                    3: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    4: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "File", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("file", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.ListBlock", (5,), {"label": "Material list"}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("material_list", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link text", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Projects marked as current.",
                            "label": "Displayed items",
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("link_text", 8),
                                ("page", 9),
                                ("displayed_items", 10),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
        migrations.AddField(
            model_name="projectpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Image",
            ),
        ),
    ]
