# Generated by Django 5.2.3

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models

import home.models.custom_blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_projectlistpage_body_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutuspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("title_block", 4),
                    ("rich_text_block", 5),
                    ("color_background_with_text_and_image_block", 8),
                    ("team_block", 14),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Subtitle", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("description", 2),
                                ("image", 3),
                            ]
                        ],
                        {},
                    ),
                    5: ("home.models.custom_blocks.RichTextBlock", (), {}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("light-yellow", "Light Yellow"),
                                ("yellow", "Yellow"),
                                ("light-red", "Light Red"),
                                ("red", "Red"),
                                ("light-gray", "Light Gray"),
                                ("gray", "Gray"),
                            ],
                            "label": "Background color",
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image position",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 6),
                                ("title", 0),
                                ("description", 2),
                                ("image_position", 7),
                                ("image", 3),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    10: ("wagtail.blocks.CharBlock", (), {"label": "Name"}),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": home.models.custom_blocks.get_team_positions,
                            "label": "Position",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 10), ("position", 11), ("image", 3)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {"label": "Members"}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("members", 13)]],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("title_block", 4),
                    ("rich_text_block", 5),
                    ("color_background_with_text_and_image_block", 8),
                    ("gallery_block", 12),
                    ("promotion_block", 15),
                    ("newsletter_signup_block", 17),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Subtitle", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("description", 2),
                                ("image", 3),
                            ]
                        ],
                        {},
                    ),
                    5: ("home.models.custom_blocks.RichTextBlock", (), {}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("light-yellow", "Light Yellow"),
                                ("yellow", "Yellow"),
                                ("light-red", "Light Red"),
                                ("red", "Red"),
                                ("light-gray", "Light Gray"),
                                ("gray", "Gray"),
                            ],
                            "label": "Background color",
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image position",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 6),
                                ("title", 0),
                                ("description", 2),
                                ("image_position", 7),
                                ("image", 3),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    10: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {"label": "Images"}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("images", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link text", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 9),
                                ("image", 3),
                                ("description", 2),
                                ("link_text", 13),
                                ("url", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Newsletter signup texts are managed under Footer settings.",
                            "label": "More settings elsewhere",
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("more_settings_elsewhere", 16)]],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
        migrations.AddField(
            model_name="newslistpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("news_list_block", 1), ("newsletter_signup_block", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    1: ("wagtail.blocks.StructBlock", [[("title", 0)]], {}),
                    2: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Newsletter signup texts are managed under Footer settings.",
                            "label": "More settings elsewhere",
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("more_settings_elsewhere", 2)]],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
        migrations.AddField(
            model_name="newspage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text_block", 0), ("gallery_block", 4)],
                blank=True,
                block_lookup={
                    0: ("home.models.custom_blocks.RichTextBlock", (), {}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {"label": "Images"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("images", 3)]],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
        migrations.AddField(
            model_name="newspage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="newspage",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news",
                to="home.projectpage",
                verbose_name="Project",
            ),
        ),
        migrations.AddField(
            model_name="newspage",
            name="publish_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Time and date of publication"
            ),
        ),
        migrations.AlterField(
            model_name="eventlistpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("title_block", 4), ("calendar_block", 6), ("past_events_block", 8)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Subtitle", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("description", 2),
                                ("image", 3),
                            ]
                        ],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Calendar of events for the current month.",
                            "label": "Displayed items",
                        },
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("displayed_items", 5)]], {}),
                    7: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    8: ("wagtail.blocks.StructBlock", [[("title", 7)]], {}),
                },
                verbose_name="Page body",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text_block", 0),
                    ("awards_and_results_block", 3),
                    ("gallery_block", 7),
                    ("material_list_block", 11),
                ],
                blank=True,
                block_lookup={
                    0: ("home.models.custom_blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link to awards", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link to results", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("awards_link", 1), ("results_link", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    6: ("wagtail.blocks.ListBlock", (5,), {"label": "Images"}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("images", 6)]],
                        {},
                    ),
                    8: ("wagtail.blocks.URLBlock", (), {"label": "Link"}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("link", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {"label": "Material list"}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("material_list", 10)]],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("title_block", 4),
                    ("upcoming_events_block", 9),
                    ("latest_news_block", 12),
                    ("current_projects_block", 15),
                    ("promotion_block", 17),
                    ("newsletter_signup_block", 19),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Subtitle", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("description", 2),
                                ("image", 3),
                            ]
                        ],
                        {},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link text", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Page",
                            "page_type": ["home.EventListPage"],
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Next upcoming events.",
                            "label": "Displayed items",
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 5),
                                ("link_text", 6),
                                ("page", 7),
                                ("displayed_items", 8),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Page",
                            "page_type": ["home.NewsListPage"],
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Latest news posts.",
                            "label": "Displayed items",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 5),
                                ("link_text", 6),
                                ("page", 10),
                                ("displayed_items", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Page",
                            "page_type": ["home.ProjectListPage"],
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Projects marked as current.",
                            "label": "Displayed items",
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 5),
                                ("link_text", 6),
                                ("page", 13),
                                ("displayed_items", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 5),
                                ("image", 3),
                                ("description", 2),
                                ("link_text", 6),
                                ("url", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Newsletter signup texts are managed under Footer settings.",
                            "label": "More settings elsewhere",
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("more_settings_elsewhere", 18)]],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
        migrations.AlterField(
            model_name="projectlistpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("current_projects_block", 4), ("past_projects_block", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link text", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Page",
                            "page_type": ["home.ProjectListPage"],
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Projects marked as current.",
                            "label": "Displayed items",
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("link_text", 1),
                                ("page", 2),
                                ("displayed_items", 3),
                            ]
                        ],
                        {},
                    ),
                    5: ("wagtail.blocks.StructBlock", [[("title", 0)]], {}),
                },
                verbose_name="Page body",
            ),
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text_block", 0),
                    ("gallery_block", 4),
                    ("material_list_block", 8),
                    ("related_news_block", 9),
                ],
                blank=True,
                block_lookup={
                    0: ("home.models.custom_blocks.RichTextBlock", (), {}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {"label": "Images"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("images", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.URLBlock", (), {"label": "Link"}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("link", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.ListBlock", (6,), {"label": "Material list"}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("material_list", 7)]],
                        {},
                    ),
                    9: ("wagtail.blocks.StructBlock", [[("title", 1)]], {}),
                },
                verbose_name="Page body",
            ),
        ),
    ]
