# Generated by Django 5.2.3 on 2025-08-01 11:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_projectpage_end_date_projectpage_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                verbose_name="Unique ID (for calendar)",
            ),
        ),
    ]
