# Generated by Django 5.2.3 on 2025-08-01 11:02

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    EventPage = apps.get_model("home", "EventPage")
    for page in EventPage.objects.all():
        page.uuid = uuid.uuid4()
        page.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_eventpage_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
