# Generated by Django 5.2.3 on 2025-08-21 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_auto_20250801_1302"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcategory",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
            ),
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="translation_key",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="teamposition",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
            ),
        ),
        migrations.AddField(
            model_name="teamposition",
            name="translation_key",
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
