# Generated by Django 5.2.3 on 2025-08-21 18:53

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_eventcategory_locale_eventcategory_translation_key_and_more"),
    ]

    # Add one operation for each model to bootstrap here
    # Note: Only include models that are in the same app!
    operations = [
        BootstrapTranslatableModel("home.EventCategory"),
        BootstrapTranslatableModel("home.TeamPosition"),
    ]
