# Generated by Django 5.2.3 on 2025-08-21 19:57

import wagtail.fields
from django.db import migrations

import home.models.settings


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_eventcategory_locale_alter_eventcategory_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="headersettings",
            name="navigation",
            field=wagtail.fields.StreamField(
                [("page_link", 3), ("external_link", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 255, "required": True},
                    ),
                    1: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": home.models.settings.get_locales_choices,
                            "label": "Show in these locales",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("page", 1), ("locales", 2)]],
                        {"icon": "link", "label": "Internal link"},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link", "required": True},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("url", 4), ("locales", 2)]],
                        {"icon": "link", "label": "External link"},
                    ),
                },
                verbose_name="Navigation",
            ),
        ),
    ]
