# Generated by Django 5.2.3 on 2025-09-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_headersettings_navigation"),
    ]

    operations = [
        migrations.AddField(
            model_name="footersettings",
            name="newsletter_signup_second_label",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Second label"
            ),
        ),
    ]
