# Generated by Django 5.2.3 on 2025-09-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_footersettings_newsletter_signup_second_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectlistpage",
            name="current_projects",
        ),
    ]
