# Generated by Django 5.2.3 on 2025-09-10 12:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_remove_projectlistpage_current_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("title_block", 4),
                    ("rich_text_block", 5),
                    ("color_background_with_text_and_image_block", 8),
                    ("gallery_block", 12),
                    ("material_list_block", 16),
                    ("promotion_block", 19),
                    ("newsletter_signup_block", 21),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Subtitle", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("description", 2),
                                ("image", 3),
                            ]
                        ],
                        {},
                    ),
                    5: ("home.models.custom_blocks.RichTextBlock", (), {}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("light-yellow", "Light Yellow"),
                                ("yellow", "Yellow"),
                                ("light-red", "Light Red"),
                                ("red", "Red"),
                                ("light-gray", "Light Gray"),
                                ("gray", "Gray"),
                            ],
                            "label": "Background color",
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image position",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 6),
                                ("title", 0),
                                ("description", 2),
                                ("image_position", 7),
                                ("image", 3),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    10: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {"label": "Images"}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("images", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.URLBlock", (), {"label": "Link"}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("link", 13)]],
                        {},
                    ),
                    15: ("wagtail.blocks.ListBlock", (14,), {"label": "Material list"}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("material_list", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link text", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 9),
                                ("image", 3),
                                ("description", 2),
                                ("link_text", 17),
                                ("url", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "Newsletter signup texts are managed under Footer settings.",
                            "label": "More settings elsewhere",
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("more_settings_elsewhere", 20)]],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
    ]
