# Generated by Django 5.2.3 on 2025-09-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_genericpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="end_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="Set time to 00:00 if it is not relevant and it will not be displayed.",
                null=True,
                verbose_name="End date and time",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="start_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="Set time to 00:00 if it is not relevant and it will not be displayed.",
                null=True,
                verbose_name="Start date and time",
            ),
        ),
    ]
