# Generated by Django 5.2.3 on 2025-10-23 08:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_alter_eventpage_body_alter_genericpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text_block", 0),
                    ("awards_and_results_block", 5),
                    ("gallery_block", 9),
                    ("material_list_block", 14),
                ],
                blank=True,
                block_lookup={
                    0: ("home.models.custom_blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty to show default label.",
                            "label": "Awards label",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link to awards", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty to show default label.",
                            "label": "Results label",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link to results", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("awards_label", 1),
                                ("awards_link", 2),
                                ("results_label", 3),
                                ("results_link", 4),
                            ]
                        ],
                        {},
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    7: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    8: ("wagtail.blocks.ListBlock", (7,), {"label": "Images"}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("images", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    11: ("wagtail.blocks.URLBlock", (), {"label": "Link"}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("description", 10), ("link", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {"label": "Material list"}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("material_list", 13)]],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
    ]
