# Generated by Django 5.2.3 on 2025-10-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_alter_eventpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="footersettings",
            name="newsletter_signup_fourth_label",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Fourth label"
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="newsletter_signup_third_label",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Third label"
            ),
        ),
    ]
