# Generated by Django 5.2.3 on 2026-02-19 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_footersettings_newsletter_signup_fourth_label_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="redirect_to_page",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, redirect to this page when visiting the home page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Redirect to page",
            ),
        ),
    ]
